include $(srctree)/drivers/misc/mediatek/Makefile.custom
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	+=  bma250.o
obj-y 	+=  cust_acc.o

